name: Docker push

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: mediamtx-with-persistence

permissions:
    id-token: write
    contents: read

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Backend build
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/amd64
                  provenance: false
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/netsocs-team/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/netsocs-team/${{ env.IMAGE_NAME }}:${{ github.sha }}
